[package]
name = "ledger"
version = "0.1.0"
authors = ["Ahmed Rafiq Ullah <ahmedrafiq47@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.7"
rocket_contrib = "0.4.7"
serde = { version = "1.0.125", features = ["derive"] }
