[package]
name = "ledger"
version = "0.1.0"
authors = ["Ahmed Rafiq Ullah <ahmedrafiq47@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
actix-web = "4.0.1"
actix-web-httpauth = "0.6.0-beta.8"
chrono = { version = "0.4.19", features = ["serde"] }
diesel = { version = "1.4.8", features = ["chrono", "postgres", "r2d2"] }
diesel_migrations = "1.4.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
rust_decimal = { version = "1.15.0", features = ["db-diesel-postgres"] }
tracing = "0.1.26"
tracing-subscriber = "0.3.11"
tracing-actix-web = "0.6.0"
jsonwebtoken = "7.2.0"
toml = "0.5.8"

[dev-dependencies]
actix-rt = "2.2.0"
futures-util = "0.3.15"
futures = "0.3.15"
rstest = "0.11.0"
