[package]
name = "ledger"
version = "0.1.0"
authors = ["Ahmed Rafiq Ullah <ahmedrafiq47@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3.2"
actix-web-httpauth = "0.5.1"
chrono = { version = "0.4.19", features = ["serde"] }
diesel = { version = "1.4.6", features = ["chrono", "postgres", "r2d2"] }
dotenv = "0.15.0"
serde = { version = "1.0.125", features = ["derive"] }
rust_decimal = { version = "1.15.0", features = ["db-diesel-postgres"] }
tracing = "0.1.26"
tracing-subscriber = "0.2.20"
jsonwebtoken = "7.2.0"

[dev-dependencies]
actix-rt = "2.2.0"
serde_json = "1.0.64"
futures-util = "0.3.15"
futures = "0.3.15"
