[package]
name = "ledger"
version = "0.1.0"
authors = ["Ahmed Rafiq Ullah <ahmedrafiq47@gmail.com>"]
edition = "2018"

[dependencies]
diesel = "1.4.6"
rocket = "0.4.7"
rocket_contrib = { version = "0.4.7", features = ["diesel_postgres_pool"] }
serde = { version = "1.0.125", features = ["derive"] }
