// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `transaction_tags` table.
    ///
    /// (Automatically generated by Diesel.)
    transaction_tags (transaction_id, tag) {
        /// The `transaction_id` column of the `transaction_tags` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        transaction_id -> Int4,
        /// The `tag` column of the `transaction_tags` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        tag -> Varchar,
    }
}

diesel::table! {
    /// Representation of the `transactions` table.
    ///
    /// (Automatically generated by Diesel.)
    transactions (id) {
        /// The `id` column of the `transactions` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `category` column of the `transactions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        category -> Varchar,
        /// The `transactee` column of the `transactions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        transactee -> Nullable<Varchar>,
        /// The `note` column of the `transactions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        note -> Nullable<Varchar>,
        /// The `date` column of the `transactions` table.
        ///
        /// Its SQL type is `Date`.
        ///
        /// (Automatically generated by Diesel.)
        date -> Date,
        /// The `amount` column of the `transactions` table.
        ///
        /// Its SQL type is `Numeric`.
        ///
        /// (Automatically generated by Diesel.)
        amount -> Numeric,
        /// The `user_id` column of the `transactions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Varchar,
    }
}

diesel::table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Varchar,
        /// The `password_hash` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        password_hash -> Varchar,
    }
}

diesel::joinable!(transaction_tags -> transactions (transaction_id));
diesel::joinable!(transactions -> users (user_id));

diesel::allow_tables_to_appear_in_same_query!(
    transaction_tags,
    transactions,
    users,
);
