name: Build

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  lambda:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - run: cargo build --release --bin ledger-lambda --no-default-features --features="lambda" --target x86_64-unknown-linux-musl
