name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  lambda:
    name: Build lambda

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2
      - name: Install musl-tools
        run: sudo apt-get install -y musl-tools
      - uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --package ledger-lambda --target x86_64-unknown-linux-musl
      - name: Create zip
        run: |
          mv target/x86_64-unknown-linux-musl/release/ledger-lambda bootstrap
          zip ledger-lambda.zip bootstrap
      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: lambda-zip
          path: ledger-lambda.zip

  release:
    name: Create release

    if: startsWith(github.event.ref, 'refs/tags/v') # if workflow is running on tag that starts with 'v'
    needs: lambda

    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: lambda-zip
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ledger-lambda.zip
